### ISSUE TITLE
Hi  BonfaceKilz

### ISSUE THREAD

**Issue by randomwangran** [BonfaceKilz/emacs.d#1]
I found the blog you write is interesting: https://www.bonfacemunyoki.com/bio/

I also find that you are a emacs user, and possible a user who visit emacs-china.org.

I think you are an expert in everything.

[I would like introduce you to the Emacs family.](https://emacs-china.org/t/topic/3374/7?u=emacs_ran)

Are you okay with it?

Ps:

I also love [One-Punch Man](https://en.wikipedia.org/wiki/One-Punch_Man). I also want to be that kinda of expert.

If you don't understand chinese, I can translate for you.

**Comment by BonfaceKilz** [comment]
Thanks dude! For the offer. I'm ok with it, but I wonder what value I'd add to the Emacs china project.

And yeah, One Punch man is the total bomb \m/\m/

**Comment by randomwangran** [comment]
I think it's up to each user's perspecitve.

For me, I like to know the people and want to be a friend who share the similar idea.

Emacs is such a tool that I feel that I like the people the way they think.

It opens a door to a new world, for me.

Reference: https://github.com/randomwangran/emacs-user-that-is-not-a-typcial-programmer/tree/master

**Comment by BonfaceKilz** [comment]
Wow. That's really impressive :+1: We can constantly keep in touch on email.  Is that OK with you? Just hit me up and I'll be sure to respond(I typically respond with 24 hours) :smile:

**Comment by randomwangran** [comment]
I personally do not like to contact with other people that I do not meet in real life using private tools.

**That's for the security issue.** I think you share the same opinion. (correct me if I am wrong)

We can always see each other or discuss idea with each on public website, e.g. your blog, or your github repos. (you can add the public link that I can access.), or  write suggestions, ideas, criticise, or anything [on my dot emacs repo](https://github.com/randomwangran/WRE) or [any other repos you have interest
](https://github.com/randomwangran?tab=repositories)
I always happy to disuss your idea.

If the private communicatation is a must, we shall do that. Am I correct?

**Comment by BonfaceKilz** [comment]
Yeah sure. The reason I suggested the public communication is because I think alot of the stuff I use is usually censored in your country(twitter).

I consider e-mails generally safe as long as you don't send weird links/ attachments. Also, I generally use [GNUS](https://www.emacswiki.org/emacs/GnusTutorial) which I find makes it easy to manage things \m/\m/

I'm open to ideas. You could try reaching out on:
- Twitter: https://twitter.com/BonfaceKilz
- Keybase: https://keybase.io/bonfacemunyoki
- Dev.to: https://dev.to/bonfacekilz
